In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd
import seaborn as sns

In [2]:
data = pd.read_csv("Social_Network_Ads.csv")
x = data.iloc[:,:-1].values 
y = data.iloc[:,-1].values

In [3]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train , y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [4]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
x_train= sd.fit_transform(x_train)
x_test = sd.transform(x_test)


In [5]:
from sklearn.linear_model import LogisticRegression
clasl = LogisticRegression()
clasl.fit(x_train, y_train)

LogisticRegression()

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [7]:
from sklearn.svm import SVC
svc = SVC(kernel='linear')
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [5]:
from sklearn.svm import SVC
svc = SVC(kernel='rbf')
svc.fit(x_train,y_train)

SVC()

In [9]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [12]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [8]:
# logistic regression prdiction 
y_pred = clasl.predict(x_test)

In [9]:
# knn clssification prediction 
y_predk = knn.predict(x_test)

In [10]:
# svc prediction
y_preds = svc.predict(x_test)


In [6]:
# kernel svc 
y_predsk = svc.predict(x_test)

In [10]:
y_preddt = dt.predict(x_test)

In [14]:
y_predrf = rf.predict(x_test)

In [11]:
# logistic regression performance 
from sklearn.metrics import confusion_matrix,accuracy_score
cf = confusion_matrix(y_test,y_pred)
ac = accuracy_score(y_test,y_pred)
print(cf)
print(ac)

[[57  1]
 [ 5 17]]
0.925


In [12]:
# knn classifier performance 
from sklearn.metrics import confusion_matrix,accuracy_score
cf = confusion_matrix(y_test,y_predk)
ac = accuracy_score(y_test,y_predk)
print(cf)
print(ac)

[[55  3]
 [ 1 21]]
0.95


In [ ]:
#  svc performance
from sklearn.metrics import confusion_matrix,accuracy_score
cf = confusion_matrix(y_test,y_preds)
ac = accuracy_score(y_test,y_preds)
print(cf)
print(ac)

In [8]:
#  svc kernel performance
from sklearn.metrics import confusion_matrix,accuracy_score
cf = confusion_matrix(y_test,y_predsk)
ac = accuracy_score(y_test,y_predsk)
print(cf)
print(ac)

[[55  3]
 [ 1 21]]
0.95


In [16]:
#  decission tree performance
from sklearn.metrics import confusion_matrix,accuracy_score
cf = confusion_matrix(y_test,y_preddt)
ac = accuracy_score(y_test,y_preddt)
print(cf)
print(ac)

[[54  4]
 [ 3 19]]
0.9125


In [15]:
#  decission tree performance
from sklearn.metrics import confusion_matrix,accuracy_score
cf = confusion_matrix(y_test,y_predrf)
ac = accuracy_score(y_test,y_predrf)
print(cf)
print(ac)

[[55  3]
 [ 2 20]]
0.9375
